# puerto del servidor
server.port=8080

# conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/sistema_turnos
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ejecutar import.sql
spring.jpa.defer-datasource-initialization=true